project/autoGate/account/urls.py
from django.urls import path
from . import views

app_name = "account"
urlpatterns = [
    path("login/", views.UserLoginView.as_view(), name="account-login"),
    path("logout/", views.UserLogoutView.as_view(), name="account-logout"),
]

project/autoGate/autoGate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("setting/", include("setting.urls", namespace="setting")),
    path('tag/', include('tag.urls', namespace='tag')),
    path('rfid/', include('rfid.urls', namespace='rfid')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('rule/', include('rule.urls', namespace='rule'))
]

project/autoGate/home/urls.py
from django.urls import path
from . import views


app_name = "home"
urlpatterns = [
    path("", views.home.as_view(), name="home"),
    path('sowh-log-home/', views.ShowLogsHomeView.as_view(), name='show_log_home')
]

project/autoGate/logs/urls.py
from django.urls import path
from . import views


app_name = "logs"

urlpatterns = [
    path("", views.LogsView.as_view(), name="logs"),
    path('show-list/', views.ShowLogsView.as_view(), name='show_logs')
]

project/autoGate/rule/urls.py
from django.urls import path
from . import views


app_name = 'rule'
urlpatterns = [
    path('', views.RuleView.as_view(), name='show_rule'),
    path('show-list-rule/', views.ListRuleView.as_view(), name='rule-list'),
    path('delete-rule/', views.DeleteRuelView.as_view(), name='rule-delete'),
    path('create-rule/', views.CreateRuleView.as_view(), name='rule-create'),
    path('update-rule/<int:rule_id>/',
         views.UpdateRuleView.as_view(), name='rule-update'),

]

project/autoGate/tag/urls.py
from django.urls import path
from . import views


app_name = "tag"
urlpatterns = [
    path("", views.TagView.as_view(), name="tag"),
    path("list-tag/", views.ListTagView.as_view(), name="tag-list"),
    path("add-tag/", views.AddTagView.as_view(), name="tag-create"),
    path('update-tag/<int:tag_id>/',
         views.UpdateTagView.as_view(), name='tag-update'),
    path('list_tag_anonymous/', views.TagAnonymous.as_view(), name='tag-anonymous'),
    path('delete-tag/<int:tag_id>/',
         views.DeleteTagView.as_view(), name='tag-delete')
]

project/autoGate/templates/inc/footer.html
<div class="card text-center">
    <div class="card-header">
        ارتباط با ما
    </div>
    <div class="card-body">
        <h5 class="card-title">09353090443 <span>مهندس مستقیمی</span></h5>
        <h5 class="card-title">09033671408 <span>مهندس جمشیدی</span></h5>
        <p class="card-text">توسعه و طراحی توسط مهندس مستفیمی و جمشیدی و فتحی</p>
        <!-- <a href="#" class="btn btn-primary">Go somewhere</a> -->
    </div>
    <div class="card-footer text-body-secondary">
    </div>
</div>

project/autoGate/templates/inc/header.html
{% load static %}
<ul class="nav bg-light p-3 shadow-sm">

    <li class="nav-item me-auto p-0">
        <a class="nav-link" href="{% url 'home:home' %}">
            <img class="p-0 m-0" src="{% static 'images/logo.png' %}" alt="لوگو"  width="50" height="50">
        </a>
    </li>

    {% if user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link active text-primary fw-bold" aria-current="page" href="{% url 'home:home' %}">خانه</a>
        </li>
        {% if user.is_staff %}
            <li class="nav-item">
                <a class="nav-link active text-primary fw-bold" aria-current="page" href="{% url 'logs:logs' %}">گزارش</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active text-primary fw-bold" aria-current="page" href="{% url 'rule:show_rule' %}">قوانین</a>
            </li>
            <li class="nav-item">
                <a class="nav-link active text-primary fw-bold" aria-current="page" href="{% url 'tag:tag' %}">خودروها</a>
            </li>
        {% endif %}
        {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link active text-primary fw-bold" aria-current="page" href="{% url 'setting:setting' %}">تنظیمات</a>
            </li>
        {% endif %}
        <li class="nav-item">
            <a class="btn btn-primary fw-bold text-white" href="{% url 'account:account-logout' %}">خروج</a>
        </li>
    {% else %}
        <li class="nav-item">
            <a class="btn btn-primary fw-bold text-white" href="{% url 'account:account-login' %}">ورود</a>
        </li>
    {% endif %}
</ul>   