project/autoGate/autoGate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("setting/", include("setting.urls", namespace="setting")),
    path('tag/', include('tag.urls', namespace='tag')),
    path('rfid/', include('rfid.urls', namespace='rfid')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('rule/', include('rule.urls', namespace='rule'))
]

project/autoGate/logs/urls.py
from django.urls import path
from . import views


app_name = "logs"

urlpatterns = [
    path("", views.LogsView.as_view(), name="logs"),
    path('show-list/', views.ShowLogsView.as_view(), name='show_logs')
]

project/autoGate/tag/urls.py
from django.urls import path
from . import views


app_name = "tag"
urlpatterns = [
    path("", views.TagView.as_view(), name="tag"),
    path("list-tag/", views.ListTagView.as_view(), name="tag-list"),
    path("add-tag/", views.AddTagView.as_view(), name="tag-create"),
    path('update-tag/<int:tag_id>/',
         views.UpdateTagView.as_view(), name='tag-update'),
    path('list_tag_anonymous/', views.TagAnonymous.as_view(), name='tag-anonymous'),
    path('delete-tag/<int:tag_id>/',
         views.DeleteTagView.as_view(), name='tag-delete')
]

project/autoGate/logs/models.py
from django.db import models
from tag.models import Tag
from setting.models import antennas
# Create your models here.


class Logs(models.Model):
    uid = models.CharField(max_length=64)

    status = models.CharField(max_length=64)

    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.uid

    class Meta:
        ordering = ["-create_at"]


class Logs(models.Model):
    tag_number = models.IntegerField()
    uid = models.CharField(max_length=64)
    status = models.CharField(max_length=64)
    rule = models.CharField(max_length=128, null=True, blank=True)
    door = models.CharField(max_length=128, null=True, blank=True)
    unit_number = models.CharField(max_length=64, null=True, blank=True)
    car_name = models.CharField(max_length=64, null=True, blank=True)
    owner_name = models.CharField(max_length=128, null=True, blank=True)
    create_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.uid} - {self.status}"

    class Meta:
        ordering = ["-create_at"]
        verbose_name = "logs"
        verbose_name_plural = "Logs"

project/autoGate/logs/forms.py
from django import forms


class LogsSearchForm(forms.Form):
    search = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['search'].widget.attrs['placeholder'] = 'جستجو'

project/autoGate/logs/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import Paginator
from .models import Logs
from .forms import LogsSearchForm

# Create your views here.


class LogsView(View):
    def get(self, request):
        return render(request, 'logs/index.html')


class ShowLogsView(View):
    form_class = LogsSearchForm

    def get(self, request):
        form = self.form_class
        print('request >>>>>>', request.GET.get('search'))

        if request.GET.get('search'):
            try:
                logs = Logs.objects.filter(
                    tag_number=request.GET.get('search'))
            except:
                logs = Logs.objects.all()
        else:
            logs = Logs.objects.all()

        page_number = request.GET.get('page', 1)

        paginator = Paginator(logs, 10)
        page_obj = paginator.get_page(page_number)

        html = render_to_string(
            'logs/partials/logs_list.html',
            {
                'logs': page_obj,
                'page_obj': page_obj,
                'form': form
            },
            request=request
        )

        return JsonResponse(
            {
                "html": html,
                'status': 200,
            },
            status=200
        )

project/autoGate/logs/templates/logs/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} گزارشات {% endblock %}
{% block link %}
<!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"> -->
    <link rel="stylesheet" href="{% static 'setting/css/bootstrap-icons.css' %}">

{% endblock %}
{% block content %}
    <div class="">
        <i class="bi bi-car-front-fill">سس</i>

        <div class="car_list" id="tagList">
        </div>
    </div>
{% endblock %}
{% block js %}
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script> -->

<script src="{% static 'setting/css/bootstrap.bundle.min.js' %}"></script>

<script>

    let selectedTagId = null;


    document.addEventListener('DOMContentLoaded', function(){
        const tagList = document.getElementById('tagList')

        function loadCarList() {

            let searchValue = window.location.search
            if (searchValue) {
                selectedTagId = searchValue   
            }else{
                searchValue = ''
            }

            console.log(searchValue)
            let url = `{% url "logs:show_logs" %}` + searchValue;
            fetch(url)
            .then(res => res.json())
            .then(data => {
                tagList.innerHTML = data.html;
            }).catch(err => {
                tagList.innerHTML = "<p>❌ خطا در بارگذاری لیست خودروها</p>";
                console.error("Error loading car list:", err);
            });
        }
        loadCarList();
        window.loadCarList = loadCarList;


        tagList.addEventListener('click', function (e) {
            if (e.target.classList.contains('pagination-link')) {

                e.preventDefault();

                console.log('hi')
                const url = e.target.getAttribute('data-url');
                fetch(url)
                    .then(res => res.json())
                    .then(data => {
                        console.log(data);
                        tagList.innerHTML = data.html;
                    });
            }
        });
    })


    setInterval(() => {
            if (selectedTagId === null) {
                window.loadCarList();
                console.log('refresh');
            } else {
                const pageStr = selectedTagId.split('?')[1].split('=')[1];
                const pageNum = parseInt(pageStr);
                if (pageNum === 1) {
                    console.log('refresh');
                    window.loadCarList();
                }
            }
        }, 20000);
</script>
{% endblock %}