project/autoGate/autoGate/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("home.urls", namespace="home")),
    path("account/", include("account.urls", namespace="account")),
    path("setting/", include("setting.urls", namespace="setting")),
    path('tag/', include('tag.urls', namespace='tag')),
    path('rfid/', include('rfid.urls', namespace='rfid')),
    path('logs/', include('logs.urls', namespace='logs')),
    path('rule/', include('rule.urls', namespace='rule'))
]

project/autoGate/tag/urls.py
from django.urls import path
from . import views


app_name = "tag"
urlpatterns = [
    path("", views.TagView.as_view(), name="tag"),
    path("list-tag/", views.ListTagView.as_view(), name="tag-list"),
    path("add-tag/", views.AddTagView.as_view(), name="tag-create"),
    path('update-tag/<int:tag_id>/',
         views.UpdateTagView.as_view(), name='tag-update'),
    path('list_tag_anonymous/', views.TagAnonymous.as_view(), name='tag-anonymous'),
    path('delete-tag/<int:tag_id>/',
         views.DeleteTagView.as_view(), name='tag-delete')
]

project/autoGate/tag/models.py
from django.db import models
from setting.models import antennas
from django.utils import timezone


# Create your models here.


class TagPermission(models.Model):

    permission_name = models.CharField(max_length=255)
    antenna = models.ManyToManyField(
        antennas, related_name="antenna_permissions", blank=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        antennas = ", ".join([a.name for a in self.antenna.all()])
        return f'{self.permission_name}'


class Tag(models.Model):
    uid = models.CharField(max_length=64, unique=True)
    tag_number = models.IntegerField(unique=True, blank=True, null=True)
    owner_name = models.CharField(max_length=64, blank=True, null=True)
    car_name = models.CharField(max_length=255, blank=True, null=True)
    pelicula = models.CharField(max_length=255, blank=True, null=True)
    number_unit = models.CharField(max_length=255, blank=True, null=True)
    rule = models.ForeignKey(
        TagPermission, on_delete=models.SET_NULL, null=True, related_name="tags_permissions")
    is_active = models.BooleanField(default=False)
    create_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.owner_name } ({self.uid})'

project/autoGate/tag/forms.py
from django import forms
from . models import Tag, TagPermission


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['uid', 'tag_number', 'owner_name', 'rule', 'is_active',
                  'car_name', 'pelicula', 'number_unit', 'tag_number']
        widgets = {
            'uid': forms.TextInput(attrs={'class': 'form-control'}),
            'owner_name': forms.TextInput(attrs={'class': 'form-control'}),
            'car_name': forms.TextInput(attrs={'class': 'form-control'}),
            'pelicula': forms.TextInput(attrs={'class': 'form-control'}),
            'number_unit': forms.TextInput(attrs={'class': 'form-control'}),
            'rule': forms.Select(attrs={'class': 'form-control'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'form-check-input'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['uid'].widget.attrs['readonly'] = True
        # self.fields['tag_number'].widget.attrs['readonly'] = True


class SearchTagForm(forms.Form):
    search_tag = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['search_tag'].widget.attrs['placeholder'] = 'جستجو'


class SearchTagAnonymousForm(forms.Form):
    search_tag_anonymous = forms.CharField(required=False, widget=forms.TextInput(
        attrs={'class': 'form-control'}))

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['search_tag_anonymous'].widget.attrs['placeholder'] = 'جستجو'

project/autoGate/tag/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from .models import Tag
from django.template.loader import render_to_string
from .forms import TagForm, SearchTagForm, SearchTagAnonymousForm
from rfid.models import AnonymousTag
from django.core.paginator import Paginator


# Create your views here.


class TagView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "tag/index.html")


class ListTagView(LoginRequiredMixin, View):
    form_class = SearchTagForm

    def get(self, request):
        form = self.form_class()
        tags = Tag.objects.all().order_by('-create_at')

        if request.GET.get('search_tag'):
            try:
                tags = Tag.objects.filter(
                    tag_number=request.GET.get('search_tag')).order_by('-create_at')
            except:
                tags = Tag.objects.all().order_by('-create_at')

        page_number = request.GET.get('page', 1)

        paginator = Paginator(tags, 10)
        page_obj = paginator.get_page(page_number)

        html = render_to_string(
            "tag/partials/list_tag.html",
            {
                "tags": page_obj,
                'page_obj': page_obj,
                'form': form
            },
            request=request
        )
        return JsonResponse(
            {
                "html": html,
                'status': 200
            },
            status=200
        )


class AddTagView(LoginRequiredMixin, View):
    def get(self, request):

        form = TagForm()
        html = render_to_string(
            "tag/partials/add_tag.html", {"form": form}, request=request)
        return JsonResponse({"form_html": html, 'status': 200}, status=200)

    def post(self, request):
        number_tag = []
        number = None

        tags = Tag.objects.all()
        for number in tags:
            number_tag.append(number.tag_number)

        if len(number_tag) == 0:
            number = 1
        else:
            for i in range(len(number_tag)+1):
                if not ((i + 1) in number_tag):
                    number = i + 1
                    break

        form = TagForm(request.POST)
        if form.is_valid():
            tag_instance = form.save(commit=False)
            tag_instance.tag_number = number
            tag_instance.save()

            return JsonResponse({"success": True, 'status': 200}, status=200)
        else:
            return JsonResponse({"success": False, "errors": form.errors, 'status': 500})


class TagAnonymous(LoginRequiredMixin, View):
    form_class = SearchTagAnonymousForm

    def get(self, request):
        form = self.form_class
        print(request.GET)
        if request.GET.get('search_tag_anonymous'):
            anonymous_tag_all = AnonymousTag.objects.filter(
                uid_anonymousTag=request.GET.get('search_tag_anonymous')).order_by('-create_at')

        else:
            anonymous_tag_all = AnonymousTag.objects.all().order_by('-create_at')

        page_number = request.GET.get('page', 1)

        paginator = Paginator(anonymous_tag_all, 10)
        page_obj = paginator.get_page(page_number)

        tags = Tag.objects.all()
        tag_list = [tag.uid for tag in tags]

        html = render_to_string(
            'tag/partials/list_anonymous_tag.html',
            {
                'tagAnonymous': page_obj,
                'tag_list': tag_list,
                'page_obj': page_obj,
                'form': form
            },
            request=request
        )

        return JsonResponse(
            {
                "html": html,
                'status': 200,
            },
            status=200
        )

    def post(self, request):
        pass


class DeleteTagView(LoginRequiredMixin, View):
    def post(self, request, tag_id):
        print('tag id : ', tag_id)
        try:
            tag = Tag.objects.get(pk=tag_id)
            print('tag >>>>>>> : ', tag)
        except Tag.DoesNotExist:
            return JsonResponse({'status': 404, 'message': 'تگ پیدا نشد'}, status=404)

        tag.delete()
        tags = Tag.objects.all()
        print('tags :', tags)
        html = render_to_string(
            'tag/partials/list_tag.html', {'tags': tags}, request=request)
        return JsonResponse({'html': html, 'status': 200}, status=200)


class UpdateTagView(LoginRequiredMixin, View):
    def get(self, request, tag_id):
        try:
            tag = Tag.objects.get(pk=tag_id)
            form = TagForm(instance=tag)
            html = render_to_string(
                'tag/partials/add_tag.html', {'form': form}, request=request)
            return JsonResponse({'status': 200, 'html': html}, status=200)
        except Exception as e:
            return JsonResponse({'status': 500, 'error': e}, status=500)

    def post(self, request, tag_id):
        try:
            tag = Tag.objects.get(pk=tag_id)
            number = tag.tag_number
            form = TagForm(request.POST, instance=tag)
            if form.is_valid():
                tag_instance = form.save(commit=False)
                tag_instance.tag_number = number
                form.save()
                return JsonResponse({"success": True, 'status': 200}, status=200)

            return JsonResponse({"success": False, "errors": form.errors, 'status': 500})
        except Exception as e:
            return JsonResponse({'status': 500, 'error': e}, status=500)

project/autoGate/tag/templates/tag/partials/add_tag.html
<div class="mb-3">
    <h5>uid</h5>
    {{ form.uid }}
    {% for error in form.uid.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>
<div class="mb-3">
    <h5>نام مالک</h5>
    {{ form.owner_name }}
    {% for error in form.owner_name.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>
<div class="mb-3">
    <h5>پلاک خودرو</h5>
    {{ form.car_name }}
    {% for error in form.car_name.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>
<div class="mb-3">
    <h5>مجتمع</h5>
    {{ form.pelicula }}
    {% for error in form.pelicula.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>
<div class="mb-3">
    <h6>واحد</h6>
    {{ form.number_unit }}
    {% for error in form.number_unit.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>
<div class="mb-3">
    <h6> قانون </h6>
    {{ form.rule }}
    {% for error in form.rule.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>
<div class="mb-3 d-flex">
    <h6>فعال</h6> &nbsp; &nbsp;
    {{ form.is_active }}
    {% for error in form.is_active.errors %}
    <div class="text-danger">{{ error }}</div>
    {% endfor %}
</div>


<!-- <h1> loded by list </h1> -->

project/autoGate/tag/templates/tag/partials/list_anonymous_tag.html
<div class="container-fluid px-4">
    <div id="car-list" class="w-100">

        <div class="bg-white p-4 rounded shadow">
            <div class="d-flex justify-content-between align-items-center flex-row-revers    mb-3">
                <h5 class="mb-0"> تگ های مدیریت</h5>
                    <div class="search-form">
                        <form action="" method="get" id="searchTagAnonymousForm">
                            <div class="input-group">
                                {{ form.search_tag_anonymous }}
                                <button type="submit" class="btn btn-primary">جستجو</button>
                            </div>
                        </form>
                    </div>
            </div>

            <table class="table table-bordered table-striped text-center align-middle w-100">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">شماره تک</th>
                        <th scope="col">زمان ثبت </th>
                        <th scope="col"> آنتن </th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tag in tagAnonymous %}
                        <tr>
                            {% if tag.uid_anonymousTag in tag_list%}
                                <td style="background-color: rgb(30, 255, 0);">{{ tag.uid_anonymousTag }}</td>
                                <td style="background-color: rgb(30, 255, 0);" >{{ tag.create_at }}</td>
                                <td style="background-color: rgb(30, 255, 0);">{{ tag.antenna }}</td>
                                <td class="d-flex justify-content-center">
                                    <button class="btn btn-sm btn-success me-1 update-antenna" disabled>افزودن</button>
                                </td>
                                
                            {% else %}
                                <td id="uid_tag" style="background-color: rgb(240, 17, 17);">{{ tag.uid_anonymousTag }}</td>
                                <td style="background-color: rgb(240, 17, 17);">{{ tag.create_at }}</td>
                                <td style="background-color: rgb(240, 17, 17);">{{ tag.antenna }}</td>

                                <td class="d-flex justify-content-center">
                                    <button class="btn btn-sm btn-success me-1 add-new-tag" data-bs-toggle="modal" data-bs-target="#createNewTagModal" data-id="{{ tag.id }}">افزودن</button>
                                </td>
                            {% endif %}
                            
                            
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="5">هیچ تگی یافت نشد.</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mt-3">
        {% if page_obj.has_previous %}
        <li class="page-item">
            {% if request.GET.search_tag_anonymous %}
            <a data-url="{% url 'tag:tag-anonymous' %}?search_tag_anonymous={{ request.GET.search_tag_anonymous }}&page={{ page_obj.previous_page_number }}"
                class="page-link pagination-link"
                href="?search_tag_anonymous={{ request.GET.search_tag_anonymous }}&page={{ page_obj.previous_page_number }}">
                قبلی
            </a>
            {% else %}
            <a data-url="{% url 'tag:tag-anonymous' %}?page={{ page_obj.previous_page_number }}"
                class="page-link pagination-link" href="?page={{ page_obj.previous_page_number }}">
                قبلی
            </a>
            {% endif %}
        </li>
        <!-- <li class="page-item">
            <a  data-url="{% url 'tag:tag-anonymous' %}?page={{ page_obj.previous_page_number }}" class="page-link pagination-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a>
        </li> -->
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
            {% if request.GET.search_tag_anonymous %}
                <a data-url="{% url 'tag:tag-anonymous' %}?search_tag_anonymous={{ request.GET.search_tag_anonymous }}&page={{ page_obj.next_page_number }}"
                    class="page-link pagination-link"
                    href="?search_tag_anonymous={{ request.GET.search_tag_anonymous }}&page={{ page_obj.next_page_number }}">صفحه
                    بعد</a>
            {% else %}
                <a data-url="{% url 'tag:tag-anonymous' %}?page={{ page_obj.next_page_number }}" class="page-link pagination-link"
                    href="?page={{ page_obj.next_page_number }}">صفحه بعد</a>
            {% endif %}
                <!-- <a  data-url="{% url 'tag:tag-anonymous' %}?page={{ page_obj.next_page_number }}" class="page-link pagination-link" href="?search_tag_anonymous={{ request.GET.search_tag_anonymous }}&page={{ page_obj.next_page_number }}">صفحه بعد</a> -->
            <!-- <a  data-url="{% url 'tag:tag-anonymous' %}?page={{ page_obj.next_page_number }}" class="page-link pagination-link" href="?page={{ page_obj.next_page_number }}">بعدی</a> -->
        </li>
        {% endif %}
    </ul>
</nav>

project/autoGate/tag/templates/tag/partials/list_tag.html
<div class="container-fluid px-4">
    <div id="car-list" class="w-100">
        <h1 class="my-4">خودرو ها</h1>

        <div class="bg-white p-4 rounded shadow">
            <div class="d-flex justify-content-between align-items-center flex-row-revers    mb-3">
                <h5 class="mb-0" > خودرو ها</h5>
                <div class="search-form">
                    <form action="" method="get" id="searchForm">
                        <div class="input-group">
                            {{ form.search_tag }}
                            <button type="submit" class="btn btn-primary">جستجو</button>
                        </div>
                    </form>
                </div>
            </div>
            <table class="table table-bordered table-striped text-center align-middle w-100">
                <thead class="table-dark">
                    <tr>
                        <th scope="col">شماره تگ</th>
                        <th scope="col">نام مالک</th>
                        <th scope="col">uid</th>
                        <th scope="col">قوانین</th>
                        <th scope="col"> پلاک خودرو</th>
                        <th scope="col"> مجتمع </th>
                        <th scope="col"> شماره واحد </th>
                        <th scope="col">وضعیت</th>
                        <th scope="col">عملیات</th>
                    </tr>
                </thead>
                <tbody>
                    {% for tag in tags %}
                    <tr>
                        <td> {{ tag.tag_number }} </td>
                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" >{{ tag.owner_name }}</td>
                        <td>{{ tag.uid }}</td>
                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" >{{ tag.rule }}</td>
                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ tag.car_name }}</td>
                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;" >{{ tag.pelicula }}</td>
                        <td style="max-width: 150px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis;">{{ tag.number_unit }}</td>
                        <td>
                            {% if tag.is_active %}
                            <span style="color: rgb(30, 255, 0);">فعال</span>
                            {% else %}
                            <span style="color: black;">غیرفعال</span>
                            {% endif %}
                        </td>
                        <td  class="d-flex justify-content-center">
                            <button data-bs-target="#UpdateTagModal" data-bs-toggle="modal" class="btn btn-sm btn-success me-1 update-tag"
                                data-id="{{ tag.id }}">ویرایش</button>
                            <button class="btn btn-sm btn-danger delete-tag" data-id="{{ tag.id }}">حذف</button>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5">هیچ آنتنی یافت نشد.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<nav aria-label="Page navigation">
    <ul class="pagination justify-content-center mt-3">
        {% if page_obj.has_previous %}
        <li class="page-item">
            <a  data-url="{% url 'tag:tag-list' %}?page={{ page_obj.previous_page_number }}" class="page-link pagination-link" href="?page={{ page_obj.previous_page_number }}">قبلی</a>
        </li>
        {% endif %}

        <li class="page-item disabled">
            <span class="page-link">صفحه {{ page_obj.number }} از {{ page_obj.paginator.num_pages }}</span>
        </li>

        {% if page_obj.has_next %}
        <li class="page-item">
            <a  data-url="{% url 'tag:tag-list' %}?page={{ page_obj.next_page_number }}" class="page-link pagination-link" href="?page={{ page_obj.next_page_number }}">بعدی</a>
        </li>
        {% endif %}
    </ul>
</nav>